# Generated by Django 5.1.2 on 2024-11-04 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('flood', models.FloatField()),
                ('drought', models.FloatField(default=0)),
                ('social_disruption', models.CharField(max_length=25)),
                ('indigenous_forecasting', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='select_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.climate')),
            ],
        ),
    ]
